version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb
    # Уберите эти строки для соответствия скриптам
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=admin123
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: unless-stopped

  # Правильный отступ для kibana
  kibana:
    image: kibana:8.17.3
    container_name: kibana_hackaton
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - node.name=kibana
      - cluster=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      # Измените на 5432:5432 для соответствия скриптам
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # Измените на учетные данные из скриптов
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped

volumes:
  redis_data:
  mongodb_data:
  mongodb_logs:
  neo4j_data:
  neo4j_logs:
  elasticsearch_data:
  postgres_data: